version: '3'
services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "5010:5010" # first number is the external port, second is the port inside the image.  No reason for them to be different, but they can be.
    env_file: .env
    # volumes:
    #  - ./src/:/code/src
    #  - ./:/code
    